// Code generated by merge_tests.go; DO NOT EDIT.
package run

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"sync/atomic"
	"testing"
	"time"
)

func TestAdvanceRunDecisionPortNilAndMissingRefBranches(t *testing.T) {
	base := time.Date(2026, 4, 3, 22, 30, 0, 0, time.UTC)
	kNil := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, nil)
	createdNil, err := kNil.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	_, err = kNil.AdvanceRun(createdNil.RunID, AdvanceRunRequest{ExpectedStateVersion: 1, StepID: "s1", StepVersion: "1", IdempotencyKey: "idem-nil", DecisionRef: DecisionRef{DecisionID: "d-nil", DecisionHash: "h-nil"}, IncomingStepSeqID: 1, InputHash: "in", OutputHash: "out"})
	assertKernelErrStatus(t, err, 409)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	kMissing := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, port)
	createdMissing, err := kMissing.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	_, err = kMissing.AdvanceRun(createdMissing.RunID, AdvanceRunRequest{ExpectedStateVersion: 1, StepID: "s1", StepVersion: "1", IdempotencyKey: "idem-missing-ref", DecisionRef: DecisionRef{DecisionID: "d-missing-ref", DecisionHash: "h-missing-ref"}, IncomingStepSeqID: 1, InputHash: "in", OutputHash: "out"})
	assertKernelErrStatus(t, err, 409)
}
func TestAbortRunTerminalAndCleanupContinuationsBranches(t *testing.T) {
	base := time.Date(2026, 4, 3, 22, 40, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, ContinuationRetention: 1 * time.Minute, IdempotencyTTL: 1 * time.Minute, RunRetention: 0}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	view, err := k.AbortRun(created.RunID, AbortRunRequest{Reason: "done"})
	mustNoErr(t, err)
	if view.State != StateAborted {
		t.Fatalf("abort should transition to aborted")
	}
	view2, err := k.AbortRun(created.RunID, AbortRunRequest{Reason: "again"})
	mustNoErr(t, err)
	if view2.State != StateAborted {
		t.Fatalf("terminal abort branch should preserve aborted state")
	}
	k.mu.Lock()
	k.continuations["active-old"] = &Continuation{ContinuationID: "active-old", RunID: created.RunID, Status: "active", ExpiresAt: base.Add(-2 * time.Minute), CreatedAt: base.Add(-3 * time.Minute)}
	deleted := k.cleanupContinuationsLocked(base)
	k.mu.Unlock()
	if deleted == 0 {
		t.Fatalf("expected old active continuation cleanup")
	}
}
func TestAdvanceDecisionReferenceValidationBranches(t *testing.T) {
	base := time.Date(2026, 4, 3, 20, 0, 0, 0, time.UTC)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, port)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	reqInvalid := validAdvanceRequest()
	reqInvalid.IdempotencyKey = "idem-invalid-hash"
	reqInvalid.DecisionRef = DecisionRef{DecisionID: "d-invalid", DecisionHash: "h-invalid", DecisionHashKind: "stable"}
	port.confirmed["d-invalid|"+created.RunID+"|"+reqInvalid.StepID] = true
	port.refs["d-invalid"] = DecisionReference{DecisionID: "d-invalid", RunID: created.RunID, StepID: reqInvalid.StepID, DecisionHash: "h-invalid", HashValid: false, HashKind: "fallback"}
	_, err = k.AdvanceRun(created.RunID, reqInvalid)
	assertKernelErrStatus(t, err, 409)
	reqRunMismatch := validAdvanceRequest()
	reqRunMismatch.IdempotencyKey = "idem-run-mismatch"
	reqRunMismatch.DecisionRef = DecisionRef{DecisionID: "d-run-mismatch", DecisionHash: "h-run", DecisionHashKind: "stable"}
	port.confirmed["d-run-mismatch|"+created.RunID+"|"+reqRunMismatch.StepID] = true
	port.refs["d-run-mismatch"] = DecisionReference{DecisionID: "d-run-mismatch", RunID: "other-run", StepID: reqRunMismatch.StepID, DecisionHash: "h-run", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, reqRunMismatch)
	assertKernelErrStatus(t, err, 409)
	reqStepMismatch := validAdvanceRequest()
	reqStepMismatch.IdempotencyKey = "idem-step-mismatch"
	reqStepMismatch.DecisionRef = DecisionRef{DecisionID: "d-step-mismatch", DecisionHash: "h-step", DecisionHashKind: "stable"}
	port.confirmed["d-step-mismatch|"+created.RunID+"|"+reqStepMismatch.StepID] = true
	port.refs["d-step-mismatch"] = DecisionReference{DecisionID: "d-step-mismatch", RunID: created.RunID, StepID: "other-step", DecisionHash: "h-step", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, reqStepMismatch)
	assertKernelErrStatus(t, err, 409)
	reqKindMismatch := validAdvanceRequest()
	reqKindMismatch.IdempotencyKey = "idem-kind-mismatch"
	reqKindMismatch.DecisionRef = DecisionRef{DecisionID: "d-kind-mismatch", DecisionHash: "h-kind", DecisionHashKind: "fallback"}
	port.confirmed["d-kind-mismatch|"+created.RunID+"|"+reqKindMismatch.StepID] = true
	port.refs["d-kind-mismatch"] = DecisionReference{DecisionID: "d-kind-mismatch", RunID: created.RunID, StepID: reqKindMismatch.StepID, DecisionHash: "h-kind", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, reqKindMismatch)
	assertKernelErrStatus(t, err, 409)
}
func TestAdvanceResponseIncludesIntegrityRootVersionAndType(t *testing.T) {
	base := time.Date(2026, 4, 3, 20, 30, 0, 0, time.UTC)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, port)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	req := validAdvanceRequest()
	req.DecisionRef = DecisionRef{DecisionID: "d-ok", DecisionHash: "h-ok", DecisionHashKind: "stable"}
	port.confirmed["d-ok|"+created.RunID+"|"+req.StepID] = true
	port.refs["d-ok"] = DecisionReference{DecisionID: "d-ok", RunID: created.RunID, StepID: req.StepID, DecisionHash: "h-ok", HashValid: true, HashKind: "stable"}
	resp, err := k.AdvanceRun(created.RunID, req)
	mustNoErr(t, err)
	if resp.RunIntegrityRootVersion == 0 {
		t.Fatalf("run integrity root version should increase on first step")
	}
	if resp.IntegrityRootType == "" {
		t.Fatalf("integrity root type should be set")
	}
}
func TestResumeUpdatesIntegrityRootConsistently(t *testing.T) {
	base := time.Date(2026, 4, 3, 21, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	parked, err := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s-park", IncomingStepSeqID: 1, TokenType: TokenTypePark, ParkReason: "wait_tool"})
	mustNoErr(t, err)
	viewAfterPark, err := k.GetRun(created.RunID)
	mustNoErr(t, err)
	parkRootVersion := viewAfterPark.RunIntegrityRootVersion
	parkLastHash := viewAfterPark.LastStepHash
	if parkRootVersion == 0 || parkLastHash == "" {
		t.Fatalf("park should establish integrity root/version: %+v", viewAfterPark)
	}
	if viewAfterPark.RunIntegrityRoot != parkLastHash {
		t.Fatalf("run_integrity_root must equal last_step_hash after park")
	}
	resumed, err := k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "tool_done", ReceiptRef: "rcpt://resume", IncomingStepSeqID: 2, ExpectedSnapshotHash: created.SnapshotHash})
	mustNoErr(t, err)
	if resumed.NewState != StateRunning {
		t.Fatalf("resume should transition to running, got=%s", resumed.NewState)
	}
	viewAfterResume, err := k.GetRun(created.RunID)
	mustNoErr(t, err)
	if viewAfterResume.RunIntegrityRoot != viewAfterResume.LastStepHash {
		t.Fatalf("run_integrity_root must equal last_step_hash after resume")
	}
	if viewAfterResume.RunIntegrityRootVersion <= parkRootVersion {
		t.Fatalf("resume should advance integrity root version: park=%d resume=%d", parkRootVersion, viewAfterResume.RunIntegrityRootVersion)
	}
	if viewAfterResume.IntegrityRootType != RootTypePartial {
		t.Fatalf("resume integrity root type mismatch: %s", viewAfterResume.IntegrityRootType)
	}
}
func TestAdvanceErrorBranches(t *testing.T) {
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{}, port)
	created, _ := k.CreateRun(validCreateRequest())
	req := validAdvanceRequest()
	_, err := k.AdvanceRun(created.RunID, req)
	assertKernelErrStatus(t, err, 422)
	req2 := validAdvanceRequest()
	req2.IdempotencyKey = "idem-2"
	req2.DecisionRef = DecisionRef{DecisionID: "d-x", DecisionHash: "h-x", DecisionHashKind: "stable"}
	port.confirmed["d-x|"+created.RunID+"|"+req2.StepID] = true
	port.refs["d-x"] = DecisionReference{DecisionID: "d-x", RunID: created.RunID, StepID: req2.StepID, DecisionHash: "h-other", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, req2)
	assertKernelErrStatus(t, err, 409)
	req3 := validAdvanceRequest()
	req3.IdempotencyKey = "idem-3"
	req3.DecisionRef = DecisionRef{DecisionID: "d-y", DecisionHash: "h-y", DecisionHashKind: "stable"}
	req3.NextState = "BAD"
	port.confirmed["d-y|"+created.RunID+"|"+req3.StepID] = true
	port.refs["d-y"] = DecisionReference{DecisionID: "d-y", RunID: created.RunID, StepID: req3.StepID, DecisionHash: "h-y", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, req3)
	assertKernelErrStatus(t, err, 422)
	req4 := validAdvanceRequest()
	req4.IdempotencyKey = "idem-4"
	req4.DecisionRef = DecisionRef{DecisionID: "d-z", DecisionHash: "h-z", DecisionHashKind: "stable"}
	req4.NextState = StateForceReviewRequired
	req4.InputHash = ""
	port.confirmed["d-z|"+created.RunID+"|"+req4.StepID] = true
	port.refs["d-z"] = DecisionReference{DecisionID: "d-z", RunID: created.RunID, StepID: req4.StepID, DecisionHash: "h-z", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, req4)
	assertKernelErrStatus(t, err, 422)
}
func TestParkErrorBranches(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	_, err := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 2, StepID: "s", IncomingStepSeqID: 1})
	assertKernelErrStatus(t, err, 409)
	_, err = k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "", IncomingStepSeqID: 1})
	assertKernelErrStatus(t, err, 422)
	_, err = k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s", IncomingStepSeqID: 1, TokenType: "bad"})
	assertKernelErrStatus(t, err, 422)
}

func TestParkRunRespectsStateTransitionGate(t *testing.T) {
	base := time.Date(2026, 4, 6, 10, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time { return base }}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)

	beforeIntegrity := len(k.StepIntegrities(created.RunID))
	beforeOutbox := len(k.Outbox())
	k.mu.RLock()
	beforeContinuations := len(k.continuations)
	k.mu.RUnlock()

	k.mu.Lock()
	r := k.runs[created.RunID]
	r.view.State = StateSafeguardHold
	r.view.StateVersion = 2
	r.view.CurrentStepSeqID = 1
	k.mu.Unlock()

	_, err = k.ParkRun(created.RunID, ParkRunRequest{
		ExpectedStateVersion: 2,
		StepID:               "s-park-blocked",
		IncomingStepSeqID:    2,
		TokenType:            TokenTypePark,
	})
	assertKernelErrStatus(t, err, 409)

	afterIntegrity := len(k.StepIntegrities(created.RunID))
	afterOutbox := len(k.Outbox())
	k.mu.RLock()
	afterContinuations := len(k.continuations)
	k.mu.RUnlock()
	if afterIntegrity != beforeIntegrity {
		t.Fatalf("forbidden park must not append synthetic step: before=%d after=%d", beforeIntegrity, afterIntegrity)
	}
	if afterContinuations != beforeContinuations {
		t.Fatalf("forbidden park must not create continuation: before=%d after=%d", beforeContinuations, afterContinuations)
	}
	if afterOutbox != beforeOutbox {
		t.Fatalf("forbidden park must not emit events: before=%d after=%d", beforeOutbox, afterOutbox)
	}
}

func TestAdvanceRunExecutionReceiptTicketGate(t *testing.T) {
	base := time.Date(2026, 4, 6, 10, 30, 0, 0, time.UTC)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}, receiptAllowed: map[string]bool{}, receiptReasons: map[string][]string{}}
	k := NewKernel(Config{Clock: func() time.Time { return base }}, port)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)

	req := validAdvanceRequest()
	req.DecisionRef = DecisionRef{DecisionID: "d-ticket-gate", DecisionHash: "h-ticket-gate", DecisionHashKind: "stable"}
	req.ExecutionReceiptRef = "ticket://missing"
	port.confirmed["d-ticket-gate|"+created.RunID+"|"+req.StepID] = true
	port.refs["d-ticket-gate"] = DecisionReference{
		DecisionID:   "d-ticket-gate",
		RunID:        created.RunID,
		StepID:       req.StepID,
		Phase:        "PRE_TOOL",
		Decision:     "allow",
		DecisionHash: "h-ticket-gate",
		HashValid:    true,
		HashKind:     "stable",
	}
	key := created.RunID + "|" + req.StepID + "|" + validCreateRequest().TenantID + "|" + req.ExecutionReceiptRef
	port.receiptAllowed[key] = false
	port.receiptReasons[key] = []string{"ticket_not_found"}

	_, err = k.AdvanceRun(created.RunID, req)
	assertKernelErrStatus(t, err, 409)
	if !hasRunEventType(k.Outbox(), "run_execution_receipt_rejected") {
		t.Fatalf("missing run_execution_receipt_rejected event")
	}
}
func TestResumeErrorBranches(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	_, err := k.ResumeRun(created.RunID, ResumeRunRequest{})
	assertKernelErrStatus(t, err, 422)
	_, err = k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: "ct-missing"})
	assertKernelErrStatus(t, err, 410)
	parked, _ := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s", IncomingStepSeqID: 1, TokenType: TokenTypePark})
	_, err = k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, IncomingStepSeqID: 1, ExpectedSnapshotHash: created.SnapshotHash})
	assertKernelErrStatus(t, err, 409)
}
func TestFlagRiskNotFound(t *testing.T) {
	k := NewKernel(Config{}, nil)
	err := k.FlagRunRisk("missing", true, false)
	assertKernelErrStatus(t, err, 404)
}
func TestHelpersCoverageRunkernel(t *testing.T) {
	k := NewKernel(Config{RunMaxLifetime: map[string]time.Duration{RiskMedium: time.Hour}}, nil)
	if got := k.maxLifetimeForRisk("unknown"); got != time.Hour {
		t.Fatalf("max lifetime fallback mismatch: %v", got)
	}
	if normalizeState("") != "" {
		t.Fatalf("normalize state empty mismatch")
	}
	if normalizeState("running") != StateRunning {
		t.Fatalf("normalize state mismatch")
	}
	if !isAllowedTransition(StateSafeguardHold, StateForceAbort) {
		t.Fatalf("expected safeguard->force_abort allowed")
	}
	if isAllowedTransition(StateCompleted, StateRunning) {
		t.Fatalf("expected completed->running forbidden")
	}
	if nextActionByState("UNKNOWN") != "halt" {
		t.Fatalf("next action default mismatch")
	}
	if tokenTypeMatchesRunState(TokenTypeApproval, StateAwaitingApproval) != true {
		t.Fatalf("approval token should match awaiting approval")
	}
	if tokenTypeMatchesRunState(TokenTypePark, StateParked) != true {
		t.Fatalf("park token should match parked")
	}
	if tokenTypeMatchesRunState(TokenTypeCallback, StateParked) != true {
		t.Fatalf("callback token should match parked")
	}
	if tokenTypeMatchesRunState(TokenTypeApproval, StateParked) {
		t.Fatalf("approval token must not match parked")
	}
	if tokenTypeMatchesRunState("unknown", StateParked) {
		t.Fatalf("unknown token must not match parked")
	}
	if nextActionByState(StateRunning) != "continue" || nextActionByState(StateParked) != "wait_resume" || nextActionByState(StateAwaitingApproval) != "wait_approval" || nextActionByState(StateReconciling) != "reconcile" || nextActionByState(StateForceReviewRequired) != "manual_review" || nextActionByState(StateForceAbort) != "stop" {
		t.Fatalf("next action known states mismatch")
	}
}
func TestTransitionMatrixCoverage(t *testing.T) {
	cases := []struct {
		from string
		to   string
		want bool
	}{{StateRunning, StateRunning, true}, {StateRunning, StateCompleted, true}, {StateRunning, StateParked, true}, {StateReconciling, StateRunning, true}, {StateReconciling, StateForceAbort, true}, {StateParked, StateRunning, true}, {StateParked, StateForceReviewRequired, true}, {StateAwaitingApproval, StateRunning, true}, {StateAwaitingApproval, StateForceAbort, true}, {StateSafeguardHold, StateForceAbort, true}, {StateSafeguardHold, StateForceReviewRequired, true}, {StateCompleted, StateRunning, false}, {StateAborted, StateRunning, false}, {"UNKNOWN", StateRunning, false}}
	for _, tc := range cases {
		if got := isAllowedTransition(tc.from, tc.to); got != tc.want {
			t.Fatalf("transition mismatch from=%s to=%s got=%v want=%v", tc.from, tc.to, got, tc.want)
		}
	}
}
func TestAnchorCoverage(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	ri, err := k.getRunLocked(created.RunID)
	mustNoErr(t, err)
	baseVersion := ri.view.RunIntegrityRootVersion
	k.anchorByStateLocked(ri, StateCompleted, "h1")
	if ri.view.RunIntegrityRoot != "h1" {
		t.Fatalf("completed anchor must update current root: got=%s", ri.view.RunIntegrityRoot)
	}
	if ri.view.RunIntegrityRootVersion <= baseVersion {
		t.Fatalf("completed anchor must advance root version: base=%d now=%d", baseVersion, ri.view.RunIntegrityRootVersion)
	}
	if ri.view.IntegrityRootType != RootTypeCompleted {
		t.Fatalf("completed anchor root type mismatch: %s", ri.view.IntegrityRootType)
	}
	if ri.view.RootAnchors.CompletedRoot != "h1" {
		t.Fatalf("completed root anchor mismatch: %s", ri.view.RootAnchors.CompletedRoot)
	}

	prevVersion := ri.view.RunIntegrityRootVersion
	k.anchorByStateLocked(ri, StateParked, "h2")
	if ri.view.RunIntegrityRoot != "h2" {
		t.Fatalf("park anchor must update current root: got=%s", ri.view.RunIntegrityRoot)
	}
	if ri.view.RunIntegrityRootVersion <= prevVersion {
		t.Fatalf("park anchor must advance root version: prev=%d now=%d", prevVersion, ri.view.RunIntegrityRootVersion)
	}
	if ri.view.IntegrityRootType != RootTypePartial {
		t.Fatalf("park anchor root type mismatch: %s", ri.view.IntegrityRootType)
	}
	if ri.view.RootAnchors.PartialRoot != "h2" {
		t.Fatalf("partial root anchor mismatch: %s", ri.view.RootAnchors.PartialRoot)
	}

	k.anchorByStateLocked(ri, StateAwaitingApproval, "h3")
	k.anchorByStateLocked(ri, StateReconciling, "h4")
	k.anchorByStateLocked(ri, StateForceReviewRequired, "h5")
	k.anchorByStateLocked(ri, StateForceAbort, "h6")
	k.anchorByStateLocked(ri, StateAborted, "h7")
	if ri.view.RootAnchors.CompletedRoot == "" || ri.view.RootAnchors.PartialRoot == "" || ri.view.RootAnchors.ReconciledRoot == "" || ri.view.RootAnchors.ReviewHoldRoot == "" || ri.view.RootAnchors.AbortedRoot == "" {
		t.Fatalf("anchor roots not fully populated: %+v", ri.view.RootAnchors)
	}
}
func TestCreateRunIdempotencyByRequestID(t *testing.T) {
	base := time.Date(2026, 4, 3, 15, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, nil)
	req := CreateRunRequest{RequestID: "req-idem-1", TenantID: "tenant-a", WorkflowID: "wf-a", WorkflowVersion: "v1", RiskTier: RiskLow, InputPayloadRef: "obj://input/1", Snapshot: SnapshotInput{PolicyBundleID: "pb", ModelProfileID: "mp", DependencyBundleID: "db", SkillBundleSetHash: "skills", ContextPolicySpaceHash: "cps"}}
	first, err := k.CreateRun(req)
	mustNoErr(t, err)
	second, err := k.CreateRun(req)
	mustNoErr(t, err)
	if first.RunID != second.RunID {
		t.Fatalf("same request_id must be idempotent: first=%s second=%s", first.RunID, second.RunID)
	}
}
func TestCreateRunRequestIDConflict(t *testing.T) {
	k := NewKernel(Config{}, nil)
	req := validCreateRequest()
	req.RequestID = "req-conflict-1"
	_, err := k.CreateRun(req)
	mustNoErr(t, err)
	req.WorkflowID = "wf-other"
	_, err = k.CreateRun(req)
	assertKernelErrStatus(t, err, 409)
}
func TestCreateRunRecreateWhenRunRecordMissing(t *testing.T) {
	k := NewKernel(Config{}, nil)
	req := validCreateRequest()
	req.RequestID = "req-recreate-1"
	first, err := k.CreateRun(req)
	mustNoErr(t, err)
	k.mu.Lock()
	delete(k.runs, first.RunID)
	k.mu.Unlock()
	second, err := k.CreateRun(req)
	mustNoErr(t, err)
	if second.RunID == first.RunID {
		t.Fatalf("new run instance should get a new run_id after previous run record is missing")
	}
}
func TestCreateRunRequestIDReusedAfterRetentionCleanup(t *testing.T) {
	base := time.Date(2026, 4, 3, 15, 15, 0, 0, time.UTC)
	now := base
	k := NewKernel(Config{Clock: func() time.Time {
		return now
	}, CreateRequestRetention: 1 * time.Minute, RunRetention: 1 * time.Minute}, nil)
	req := validCreateRequest()
	req.RequestID = "req-retention-reuse-1"
	first, err := k.CreateRun(req)
	mustNoErr(t, err)
	now = base.Add(30 * time.Second)
	second, err := k.CreateRun(req)
	mustNoErr(t, err)
	if second.RunID != first.RunID {
		t.Fatalf("within retention window, same request_id must be idempotent")
	}
	now = base.Add(5 * time.Minute)
	k.mu.Lock()
	ri := k.runs[first.RunID]
	ri.view.State = StateAborted
	ri.view.UpdatedAt = base.Add(-5 * time.Minute)
	k.mu.Unlock()
	_ = k.MaintenanceSweep(now)
	third, err := k.CreateRun(req)
	mustNoErr(t, err)
	if third.RunID == first.RunID {
		t.Fatalf("after retention cleanup, same request_id should create a new run")
	}
}
func TestAbortAllowsResubmitSameRequestID(t *testing.T) {
	k := NewKernel(Config{}, nil)
	req := validCreateRequest()
	req.RequestID = "req-abort-resubmit-1"
	first, err := k.CreateRun(req)
	mustNoErr(t, err)
	_, err = k.AbortRun(first.RunID, AbortRunRequest{Reason: "manual"})
	mustNoErr(t, err)
	second, err := k.CreateRun(req)
	mustNoErr(t, err)
	if second.RunID == first.RunID {
		t.Fatalf("after terminal abort, same request_id should be able to create a new run instance")
	}
}
func TestResumeApprovalTokenStateFlow(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	parked, err := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "step-1", IncomingStepSeqID: 1, TokenType: TokenTypeApproval, ParkReason: "wait_approval"})
	mustNoErr(t, err)
	if parked.NewState != StateAwaitingApproval {
		t.Fatalf("approval token must park into awaiting_approval, got=%s", parked.NewState)
	}
	resumed, err := k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "resume", IncomingStepSeqID: 2, ExpectedSnapshotHash: created.SnapshotHash})
	mustNoErr(t, err)
	if resumed.NewState != StateRunning {
		t.Fatalf("resume should return running state, got=%s", resumed.NewState)
	}
}
func TestAdvanceTerminalCleansRunScopedCaches(t *testing.T) {
	base := time.Date(2026, 4, 3, 15, 30, 0, 0, time.UTC)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, port)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	req := validAdvanceRequest()
	req.NextState = StateCompleted
	req.DecisionRef = DecisionRef{DecisionID: "d-clean", DecisionHash: "h-clean", DecisionHashKind: "stable"}
	port.confirmed["d-clean|"+created.RunID+"|"+req.StepID] = true
	port.refs["d-clean"] = DecisionReference{DecisionID: "d-clean", RunID: created.RunID, StepID: req.StepID, DecisionHash: "h-clean", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, req)
	mustNoErr(t, err)
	idemKey := created.RunID + "|" + req.StepID + "|" + req.StepVersion + "|" + req.IdempotencyKey
	k.mu.RLock()
	_, idemExists := k.idempotency[idemKey]
	contCount := len(k.continuations)
	k.mu.RUnlock()
	if idemExists {
		t.Fatalf("terminal transition must clean run-scoped idempotency")
	}
	if contCount != 0 {
		t.Fatalf("terminal transition must clean run-scoped continuations")
	}
}
func TestMaintenanceCleanupFunctions(t *testing.T) {
	base := time.Date(2026, 4, 3, 16, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, ContinuationTTL: 1 * time.Minute, ContinuationRetention: 1 * time.Minute, IdempotencyTTL: 1 * time.Minute, RunRetention: 1 * time.Minute, CreateRequestRetention: 1 * time.Minute}, nil)
	req := validCreateRequest()
	req.RequestID = "req-maintenance-1"
	created, err := k.CreateRun(req)
	mustNoErr(t, err)
	consumedAt := base.Add(-3 * time.Minute)
	k.mu.Lock()
	ri := k.runs[created.RunID]
	ri.view.State = StateAborted
	ri.view.UpdatedAt = base.Add(-3 * time.Minute)
	k.stepIntegrity[created.RunID] = append(k.stepIntegrity[created.RunID], StepIntegrity{RunID: created.RunID, StepID: "s1"})
	k.idempotency["idem-old"] = idempotencyEntry{RunID: created.RunID, Response: AdvanceRunResponse{NewState: StateRunning}, CreatedAt: base.Add(-3 * time.Minute), LastAccessAt: base.Add(-3 * time.Minute)}
	k.continuations["ct-consumed"] = &Continuation{ContinuationID: "ct-consumed", RunID: created.RunID, Status: "consumed", ExpiresAt: base.Add(-4 * time.Minute), ConsumedAt: &consumedAt}
	k.continuations["ct-expired"] = &Continuation{ContinuationID: "ct-expired", RunID: "run-x", Status: "expired", ExpiresAt: base.Add(-4 * time.Minute)}
	k.continuations["ct-active-old"] = &Continuation{ContinuationID: "ct-active-old", RunID: "run-y", Status: "active", ExpiresAt: base.Add(-4 * time.Minute)}
	k.createRuns["tenant-z|req-z"] = createRunEntry{RunID: "run-z", RequestHash: "hash-z", Response: CreateRunResponse{RunID: "run-z"}, CreatedAt: base.Add(-3 * time.Minute), LastAccessAt: base.Add(-3 * time.Minute)}
	result := SweepResult{}
	k.applyMaintenanceLocked(base, &result)
	k.mu.Unlock()
	if result.DeletedRuns == 0 || result.DeletedContinuations == 0 || result.DeletedIdempotency == 0 {
		t.Fatalf("expected cleanup counters to increase: %+v", result)
	}
	if result.DeletedCreateRequests == 0 {
		t.Fatalf("expected create-request cleanup counter to increase: %+v", result)
	}
	k.mu.RLock()
	_, runExists := k.runs[created.RunID]
	_, stepExists := k.stepIntegrity[created.RunID]
	k.mu.RUnlock()
	if runExists || stepExists {
		t.Fatalf("terminal run cleanup should remove run and step integrity")
	}
}
func TestMaintenanceSweepAPI(t *testing.T) {
	base := time.Date(2026, 4, 3, 19, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, ContinuationRetention: 1 * time.Minute, IdempotencyTTL: 1 * time.Minute, RunRetention: 1 * time.Minute, CreateRequestRetention: 1 * time.Minute}, nil)
	req := validCreateRequest()
	req.RequestID = "req-maint-api"
	created, err := k.CreateRun(req)
	mustNoErr(t, err)
	k.mu.Lock()
	k.runs[created.RunID].view.State = StateAborted
	k.runs[created.RunID].view.UpdatedAt = base.Add(-2 * time.Minute)
	k.idempotency["idem-maint-api"] = idempotencyEntry{RunID: created.RunID, Response: AdvanceRunResponse{NewState: StateRunning}, CreatedAt: base.Add(-2 * time.Minute), LastAccessAt: base.Add(-2 * time.Minute)}
	k.mu.Unlock()
	out := k.MaintenanceSweep(base)
	if out.DeletedRuns == 0 || out.DeletedIdempotency == 0 {
		t.Fatalf("maintenance sweep should delete stale entries: %+v", out)
	}
}
func TestHashJSONWithStatusErrorSentinel(t *testing.T) {
	type bad struct {
		C chan int `json:"c"`
	}
	h, ok := hashJSONWithStatus(bad{C: make(chan int)})
	if ok {
		t.Fatalf("marshal failure should report ok=false")
	}
	if !strings.HasPrefix(h, "err_") || !isErrorHash(h) {
		t.Fatalf("marshal failure hash must carry err_ sentinel: %q", h)
	}
	if got := hashJSON(bad{C: make(chan int)}); got != "" {
		t.Fatalf("hashJSON must return empty string on marshal failure, got=%q", got)
	}
}
func TestForcedMarshalFailuresCoverage(t *testing.T) {
	original := marshalJSON
	defer func() {
		marshalJSON = original
	}()
	k := NewKernel(Config{}, nil)
	marshalJSON = func(v interface{}) ([]byte, error) {
		return nil, errors.New("forced-marshal-failure")
	}
	_, err := k.CreateRun(validCreateRequest())
	assertKernelErrStatus(t, err, 500)
}
func TestForcedMarshalFailuresAdvanceParkResumeAndSweep(t *testing.T) {
	base := time.Date(2026, 4, 3, 20, 0, 0, 0, time.UTC)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, RunMaxLifetime: map[string]time.Duration{RiskLow: time.Minute, RiskMedium: time.Minute, RiskHigh: time.Minute, RiskCritical: time.Minute}, ZombieNoProgressWindow: time.Minute}, port)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	original := marshalJSON
	defer func() {
		marshalJSON = original
	}()
	marshalJSON = func(v interface{}) ([]byte, error) {
		return nil, errors.New("forced-marshal-failure")
	}
	adv := validAdvanceRequest()
	adv.DecisionRef = DecisionRef{DecisionID: "d-force", DecisionHash: "h-force", DecisionHashKind: "stable"}
	port.confirmed["d-force|"+created.RunID+"|"+adv.StepID] = true
	port.refs["d-force"] = DecisionReference{DecisionID: "d-force", RunID: created.RunID, StepID: adv.StepID, DecisionHash: "h-force", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, adv)
	assertKernelErrStatus(t, err, 500)
	marshalJSON = original
	k2 := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, nil)
	created2, err := k2.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	marshalJSON = func(v interface{}) ([]byte, error) {
		return nil, errors.New("forced-marshal-failure")
	}
	_, err = k2.ParkRun(created2.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s1", IncomingStepSeqID: 1, TokenType: TokenTypePark})
	assertKernelErrStatus(t, err, 500)
	marshalJSON = original
	k3 := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, nil)
	created3, err := k3.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	parked, err := k3.ParkRun(created3.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s1", IncomingStepSeqID: 1, TokenType: TokenTypePark})
	mustNoErr(t, err)
	marshalJSON = func(v interface{}) ([]byte, error) {
		return nil, errors.New("forced-marshal-failure")
	}
	_, err = k3.ResumeRun(created3.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "forced-failure", IncomingStepSeqID: 2, ExpectedSnapshotHash: created3.SnapshotHash})
	assertKernelErrStatus(t, err, 500)
	marshalJSON = original
	k4 := NewKernel(Config{Clock: func() time.Time {
		return base
	}, RunMaxLifetime: map[string]time.Duration{RiskLow: time.Minute, RiskMedium: time.Minute, RiskHigh: time.Minute, RiskCritical: time.Minute}, ZombieNoProgressWindow: time.Minute}, nil)
	rSweep, err := k4.CreateRun(validCreateRequestWithRisk(RiskHigh))
	mustNoErr(t, err)
	_ = k4.FlagRunRisk(rSweep.RunID, true, false)
	marshalJSON = func(v interface{}) ([]byte, error) {
		return nil, errors.New("forced-marshal-failure")
	}
	ttl := k4.SweepTTL(base.Add(2 * time.Minute))
	if ttl.SkippedIntegrityErrors == 0 {
		t.Fatalf("expected skipped integrity errors on forced marshal failure")
	}
}
func TestSweepTTLAndZombieAdditionalBranches(t *testing.T) {
	base := time.Date(2026, 4, 3, 17, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, SweepBatchLimit: 10, ZombieNoProgressWindow: 1 * time.Minute, RunMaxLifetime: map[string]time.Duration{RiskLow: 1 * time.Minute, RiskMedium: 1 * time.Minute, RiskHigh: 1 * time.Minute, RiskCritical: 1 * time.Minute}}, nil)
	r1, _ := k.CreateRun(validCreateRequestWithRisk(RiskLow))
	r2, _ := k.CreateRun(validCreateRequestWithRisk(RiskMedium))
	r3, _ := k.CreateRun(validCreateRequestWithRisk(RiskHigh))
	k.mu.Lock()
	k.runs[r1.RunID].view.State = StateCompleted
	k.runs[r2.RunID].maxLifetime = 0
	k.runs[r3.RunID].view.CreatedAt = base.Add(-2 * time.Minute)
	k.runs[r3.RunID].view.LastProgressAt = base.Add(-30 * time.Second)
	k.mu.Unlock()
	ttl := k.SweepTTL(base.Add(2 * time.Minute))
	if ttl.Scanned == 0 {
		t.Fatalf("expected ttl sweep to scan runs")
	}
	r4, _ := k.CreateRun(validCreateRequestWithRisk(RiskMedium))
	_ = k.FlagRunRisk(r4.RunID, true, false)
	z1 := k.SweepZombie(base.Add(5 * time.Minute))
	if z1.Scanned == 0 {
		t.Fatalf("expected zombie sweep scan")
	}
	z2 := k.SweepZombie(base.Add(6 * time.Minute))
	if z2.ZombieTerminatedCount == 0 {
		t.Fatalf("expected zombie termination on second scan")
	}
}
func TestSweepBatchLimitAndTransitionHelpers(t *testing.T) {
	base := time.Date(2026, 4, 3, 18, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, SweepBatchLimit: 1, RunMaxLifetime: map[string]time.Duration{RiskLow: 1 * time.Minute, RiskMedium: 1 * time.Minute, RiskHigh: 1 * time.Minute, RiskCritical: 1 * time.Minute}}, nil)
	_, _ = k.CreateRun(validCreateRequestWithRisk(RiskLow))
	_, _ = k.CreateRun(validCreateRequestWithRisk(RiskLow))
	ttl := k.SweepTTL(base.Add(2 * time.Minute))
	if ttl.Scanned != 1 {
		t.Fatalf("batch limit should cap scans to 1, got=%d", ttl.Scanned)
	}
	if !isAllowedTransition(StateReconciling, StateCompleted) {
		t.Fatalf("reconciling -> completed should be allowed")
	}
	if !isAllowedTransition(StateAwaitingApproval, StateForceAbort) {
		t.Fatalf("awaiting approval -> force abort should be allowed")
	}
	if !isAllowedTransition(StateParked, StateForceReviewRequired) {
		t.Fatalf("parked -> force review required should be allowed")
	}
	if tokenTypeMatchesRunState(TokenTypeCallback, StateAwaitingApproval) {
		t.Fatalf("callback token must not resume awaiting approval")
	}
}
func TestCleanupRunScopedCachesDirect(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	k.mu.Lock()
	k.idempotency["idem-x"] = idempotencyEntry{RunID: created.RunID, Response: AdvanceRunResponse{NewState: StateRunning}, CreatedAt: time.Now(), LastAccessAt: time.Now()}
	k.continuations["ct-x"] = &Continuation{ContinuationID: "ct-x", RunID: created.RunID, Status: "active", ExpiresAt: time.Now().Add(time.Minute)}
	k.cleanupRunScopedCachesLocked(created.RunID)
	_, idemExists := k.idempotency["idem-x"]
	_, contExists := k.continuations["ct-x"]
	k.mu.Unlock()
	if idemExists || contExists {
		t.Fatalf("run-scoped cache cleanup should remove idempotency and continuation")
	}
}
func TestCleanupHelpersBranchCoverage(t *testing.T) {
	now := time.Date(2026, 4, 3, 21, 0, 0, 0, time.UTC)
	k := NewKernel(Config{ContinuationRetention: 1 * time.Minute, IdempotencyTTL: 1 * time.Minute, CreateRequestRetention: 1 * time.Minute, RunRetention: 1 * time.Minute}, nil)
	oldConsumed := now.Add(-3 * time.Minute)
	k.continuations["c-consumed-keep"] = &Continuation{ContinuationID: "c-consumed-keep", Status: "consumed", ExpiresAt: now.Add(-10 * time.Minute)}
	k.continuations["c-consumed-del"] = &Continuation{ContinuationID: "c-consumed-del", Status: "consumed", ExpiresAt: now.Add(-10 * time.Minute), ConsumedAt: &oldConsumed}
	k.continuations["c-expired-del"] = &Continuation{ContinuationID: "c-expired-del", Status: "expired", ExpiresAt: now.Add(-10 * time.Minute)}
	k.continuations["c-active-mark-expired"] = &Continuation{ContinuationID: "c-active-mark-expired", Status: "active", ExpiresAt: now.Add(-30 * time.Second)}
	k.continuations["c-active-del"] = &Continuation{ContinuationID: "c-active-del", Status: "active", ExpiresAt: now.Add(-10 * time.Minute)}
	deletedCont := k.cleanupContinuationsLocked(now)
	if deletedCont == 0 {
		t.Fatalf("expected continuation cleanup to delete stale entries")
	}
	if c, ok := k.continuations["c-active-mark-expired"]; ok && c.Status != "expired" {
		t.Fatalf("active continuation past ttl should be marked expired")
	}
	k.idempotency["idem-del-created-old"] = idempotencyEntry{RunID: "run-x", Response: AdvanceRunResponse{NewState: StateRunning}, CreatedAt: now.Add(-3 * time.Minute)}
	k.idempotency["idem-keep-recent"] = idempotencyEntry{RunID: "run-y", Response: AdvanceRunResponse{NewState: StateRunning}, CreatedAt: now, LastAccessAt: now}
	deletedIdem := k.cleanupIdempotencyLocked(now)
	if deletedIdem == 0 {
		t.Fatalf("expected idempotency cleanup to delete stale entry")
	}
	k.createRuns["tenant-a|req-old"] = createRunEntry{RunID: "run-old", RequestHash: "h-old", CreatedAt: now.Add(-3 * time.Minute)}
	k.createRuns["tenant-a|req-new"] = createRunEntry{RunID: "run-new", RequestHash: "h-new", CreatedAt: now, LastAccessAt: now}
	deletedCreate := k.cleanupCreateRunsLocked(now)
	if deletedCreate == 0 {
		t.Fatalf("expected createRuns cleanup to delete stale entry")
	}
	kNoRetention := NewKernel(Config{RunRetention: 0}, nil)
	req := validCreateRequest()
	req.RequestID = "req-terminal-no-retention"
	createdNoRetention, err := kNoRetention.CreateRun(req)
	mustNoErr(t, err)
	kNoRetention.runs[createdNoRetention.RunID].view.State = StateAborted
	runsDeleted := kNoRetention.cleanupTerminalRunsLocked(now.Add(10 * time.Minute))
	if runsDeleted != 0 {
		t.Fatalf("run retention disabled should not delete runs")
	}
	kRetention := NewKernel(Config{RunRetention: 1 * time.Minute}, nil)
	req2 := validCreateRequest()
	req2.RequestID = "req-terminal-retention"
	createdRetention, err := kRetention.CreateRun(req2)
	mustNoErr(t, err)
	kRetention.runs[createdRetention.RunID].view.State = StateRunning
	kRetention.runs[createdRetention.RunID].view.UpdatedAt = now.Add(-3 * time.Minute)
	runsDeleted2 := kRetention.cleanupTerminalRunsLocked(now)
	if runsDeleted2 != 0 {
		t.Fatalf("non-terminal runs must not be deleted")
	}
}
func TestRunOutboxTrimRetentionAndDrain(t *testing.T) {
	base := time.Date(2026, 4, 3, 22, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, OutboxMaxEvents: 2, OutboxRetention: 1 * time.Minute}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	_, err = k.AbortRun(created.RunID, AbortRunRequest{Reason: "trim-test"})
	mustNoErr(t, err)
	_, err = k.CreateRun(validCreateRequestWithWorkflow("wf-outbox-2"))
	mustNoErr(t, err)
	out := k.Outbox()
	if len(out) != 2 {
		t.Fatalf("outbox max events should trim to bound=2, got=%d", len(out))
	}
	drained := k.DrainOutbox(1)
	if len(drained) != 1 {
		t.Fatalf("expected drain one event, got=%d", len(drained))
	}
	k.mu.Lock()
	for i := range k.outbox {
		k.outbox[i].EventTS = base.Add(-2 * time.Minute)
	}
	k.mu.Unlock()
	res := k.MaintenanceSweep(base)
	if res.OutboxTrimmed == 0 {
		t.Fatalf("expected maintenance sweep to trim retained outbox events")
	}
}
func TestCleanupContinuationsNonDeletionBranches(t *testing.T) {
	now := time.Date(2026, 4, 3, 22, 0, 0, 0, time.UTC)
	k := NewKernel(Config{ContinuationRetention: 1 * time.Minute}, nil)
	consumedRecent := now.Add(-30 * time.Second)
	k.continuations["consumed-recent"] = &Continuation{ContinuationID: "consumed-recent", Status: "consumed", ConsumedAt: &consumedRecent, ExpiresAt: now.Add(-10 * time.Minute)}
	k.continuations["expired-recent"] = &Continuation{ContinuationID: "expired-recent", Status: "expired", ExpiresAt: now.Add(-30 * time.Second)}
	k.continuations["active-future"] = &Continuation{ContinuationID: "active-future", Status: "active", ExpiresAt: now.Add(30 * time.Second)}
	deleted := k.cleanupContinuationsLocked(now)
	if deleted != 0 {
		t.Fatalf("expected zero deletions for recent/future continuations, got=%d", deleted)
	}
	if _, ok := k.continuations["consumed-recent"]; !ok {
		t.Fatalf("recent consumed continuation should remain")
	}
	if _, ok := k.continuations["expired-recent"]; !ok {
		t.Fatalf("recent expired continuation should remain")
	}
	if c, ok := k.continuations["active-future"]; !ok || c.Status != "active" {
		t.Fatalf("future active continuation should remain active")
	}
}
func TestDrainOutboxBranchCoverage(t *testing.T) {
	k := NewKernel(Config{}, nil)
	if drained := k.DrainOutbox(1); drained != nil {
		t.Fatalf("empty outbox should return nil drain result")
	}
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	_, err = k.AbortRun(created.RunID, AbortRunRequest{Reason: "drain-branches"})
	mustNoErr(t, err)
	before := len(k.Outbox())
	if before == 0 {
		t.Fatalf("expected outbox events")
	}
	if drained := k.DrainOutbox(0); drained != nil {
		t.Fatalf("non-positive drain limit should return nil")
	}
	if len(k.Outbox()) != before {
		t.Fatalf("drain with limit=0 must not mutate outbox")
	}
	all := k.DrainOutbox(999)
	if len(all) != before {
		t.Fatalf("expected full drain when limit exceeds outbox size: got=%d want=%d", len(all), before)
	}
	if len(k.Outbox()) != 0 {
		t.Fatalf("outbox should be empty after full drain")
	}
}
func TestCleanupOutboxNoTrimBranches(t *testing.T) {
	now := time.Date(2026, 4, 3, 23, 30, 0, 0, time.UTC)
	k := NewKernel(Config{OutboxMaxEvents: 10, OutboxRetention: 0}, nil)
	k.mu.Lock()
	k.outbox = []KernelEvent{{EventID: "e1", EventTS: now}, {EventID: "e2", EventTS: now}}
	trimmed := k.cleanupOutboxLocked(now)
	k.mu.Unlock()
	if trimmed != 0 {
		t.Fatalf("expected no outbox trim, got=%d", trimmed)
	}
}
func TestParkDefaultTokenTypeBranch(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	parked, err := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s-default-token", IncomingStepSeqID: 1, TokenType: ""})
	mustNoErr(t, err)
	if parked.ContinuationType != TokenTypePark {
		t.Fatalf("empty token_type should default to park, got=%s", parked.ContinuationType)
	}
}
func TestSweepZombieDetailedBranches(t *testing.T) {
	base := time.Date(2026, 4, 3, 23, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, ZombieNoProgressWindow: 1 * time.Minute, SweepBatchLimit: 10}, nil)
	terminal, _ := k.CreateRun(validCreateRequestWithRisk(RiskLow))
	recent, _ := k.CreateRun(validCreateRequestWithRisk(RiskLow))
	oldReview, _ := k.CreateRun(validCreateRequestWithRisk(RiskLow))
	oldAbort, _ := k.CreateRun(validCreateRequestWithRisk(RiskHigh))
	k.mu.Lock()
	k.runs[terminal.RunID].view.State = StateCompleted
	k.runs[recent.RunID].view.LastProgressAt = base.Add(-30 * time.Second)
	k.runs[recent.RunID].noProgressScans = 5
	k.runs[oldReview.RunID].view.LastProgressAt = base.Add(-5 * time.Minute)
	k.runs[oldAbort.RunID].view.LastProgressAt = base.Add(-5 * time.Minute)
	k.runs[oldAbort.RunID].securityRisk = true
	k.mu.Unlock()
	first := k.SweepZombie(base)
	if first.ZombieTerminatedCount != 0 {
		t.Fatalf("first zombie scan should not terminate, got=%+v", first)
	}
	k.mu.RLock()
	if k.runs[recent.RunID].noProgressScans != 0 {
		k.mu.RUnlock()
		t.Fatalf("recent-progress run should reset noProgressScans on first scan")
	}
	k.mu.RUnlock()
	second := k.SweepZombie(base.Add(2 * time.Minute))
	if second.ZombieTerminatedCount == 0 {
		t.Fatalf("second zombie scan should terminate stale runs")
	}
	k.mu.RLock()
	reviewState := k.runs[oldReview.RunID].view.State
	abortState := k.runs[oldAbort.RunID].view.State
	k.mu.RUnlock()
	if reviewState != StateForceReviewRequired {
		t.Fatalf("non-risk stale run should force review, got=%s", reviewState)
	}
	if abortState != StateForceAbort {
		t.Fatalf("risk stale run should force abort, got=%s", abortState)
	}
}
func TestRunEventEnvelopeFields(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	if created.RunID == "" {
		t.Fatalf("create run should succeed")
	}
	events := k.Outbox()
	if len(events) == 0 {
		t.Fatalf("expected run outbox events")
	}
	last := events[len(events)-1]
	if last.SchemaVersion != 1 {
		t.Fatalf("unexpected schema version: %d", last.SchemaVersion)
	}
	if last.SourceComponent != "run_kernel" {
		t.Fatalf("unexpected source component: %s", last.SourceComponent)
	}
	if strings.TrimSpace(last.PayloadRef) == "" {
		t.Fatalf("payload_ref should be set")
	}
	if !last.PayloadHashValid || strings.TrimSpace(last.PayloadHash) == "" {
		t.Fatalf("payload_hash should be valid for run event")
	}
	if last.EvidenceGrade != "operational" {
		t.Fatalf("create event should be operational, got=%s", last.EvidenceGrade)
	}
	if last.PayloadIntegrityRequired {
		t.Fatalf("create event must not require payload integrity")
	}
}

func TestRunAuditEventEnvelopePolicy(t *testing.T) {
	k := NewKernel(Config{}, nil)
	k.emitProgressMonotonicityViolation("run-audit", "step-audit", 1, 2, time.Now())
	events := k.Outbox()
	if len(events) == 0 {
		t.Fatalf("expected run audit events")
	}
	last := events[len(events)-1]
	if last.EventType != "irreversible_progress_violation_event" {
		t.Fatalf("expected canonical audit event, got=%s", last.EventType)
	}
	if last.EvidenceGrade != "audit" {
		t.Fatalf("expected audit evidence grade, got=%s", last.EvidenceGrade)
	}
	if !last.PayloadIntegrityRequired {
		t.Fatalf("audit event must require payload integrity")
	}
	grade, required := runEventEvidencePolicy("run_execution_receipt_rejected")
	if grade != "audit" || !required {
		t.Fatalf("run_execution_receipt_rejected must be audit/required, got grade=%s required=%v", grade, required)
	}
}

type fakeDecisionPort struct {
	confirmed      map[string]bool
	refs           map[string]DecisionReference
	receiptAllowed map[string]bool
	receiptReasons map[string][]string
}

func (f *fakeDecisionPort) IsDecisionConfirmed(decisionID, runID, stepID string) bool {
	return f.confirmed[decisionID+"|"+runID+"|"+stepID]
}
func (f *fakeDecisionPort) IsDecisionConfirmedWithOwner(decisionID, runID, stepID string, _ int, _ string) bool {
	return f.IsDecisionConfirmed(decisionID, runID, stepID)
}
func (f *fakeDecisionPort) GetDecisionReference(decisionID string) (DecisionReference, bool) {
	v, ok := f.refs[decisionID]
	return v, ok
}
func (f *fakeDecisionPort) ValidateExecutionReceiptForRun(runID, stepID, tenantID, executionReceiptRef string, _ map[string]float64, _ time.Time) (bool, []string) {
	key := runID + "|" + stepID + "|" + tenantID + "|" + executionReceiptRef
	if f.receiptAllowed != nil {
		if allowed, ok := f.receiptAllowed[key]; ok {
			if !allowed {
				if reasons, ok := f.receiptReasons[key]; ok {
					return false, append([]string(nil), reasons...)
				}
				return false, []string{"execution_receipt_ticket_invalid"}
			}
			return true, nil
		}
	}
	if strings.TrimSpace(executionReceiptRef) == "" {
		return false, []string{"execution_receipt_ticket_missing"}
	}
	// Default test behavior: accept receipt refs unless explicitly overridden.
	return true, nil
}

type runCaseFile struct {
	Cases []runCase `json:"cases"`
}
type runCase struct {
	Name    string            `json:"name"`
	Create  CreateRunRequest  `json:"create"`
	Advance AdvanceRunRequest `json:"advance,omitempty"`
	Park    ParkRunRequest    `json:"park,omitempty"`
}

func TestRunKernel_FromTestData(t *testing.T) {
	cases := loadRunCases(t)
	for _, tc := range cases {
		tc := tc
		t.Run(tc.Name, func(t *testing.T) {
			base := time.Date(2026, 4, 3, 13, 0, 0, 0, time.UTC)
			port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
			k := NewKernel(Config{Clock: func() time.Time {
				return base
			}}, port)
			created, err := k.CreateRun(tc.Create)
			mustNoErr(t, err)
			if created.RunID == "" || created.SnapshotHash == "" {
				t.Fatalf("invalid create response: %+v", created)
			}
			if tc.Advance.StepID != "" {
				tc.Advance.ExpectedStateVersion = 1
				tc.Advance.DecisionRef = DecisionRef{DecisionID: "dec-" + tc.Name, DecisionHash: "dh-" + tc.Name, DecisionHashKind: "stable"}
				port.confirmed[tc.Advance.DecisionRef.DecisionID+"|"+created.RunID+"|"+tc.Advance.StepID] = true
				port.refs[tc.Advance.DecisionRef.DecisionID] = DecisionReference{DecisionID: tc.Advance.DecisionRef.DecisionID, RunID: created.RunID, StepID: tc.Advance.StepID, DecisionHash: tc.Advance.DecisionRef.DecisionHash, HashValid: true, HashKind: "stable"}
				resp, err := k.AdvanceRun(created.RunID, tc.Advance)
				mustNoErr(t, err)
				if resp.StepHash == "" || resp.StateVersion != 2 {
					t.Fatalf("invalid advance response: %+v", resp)
				}
			}
			if tc.Park.StepID != "" {
				tc.Park.ExpectedStateVersion = 1
				parked, err := k.ParkRun(created.RunID, tc.Park)
				mustNoErr(t, err)
				if parked.NewState != StateParked || parked.ContinuationToken == "" {
					t.Fatalf("invalid park response: %+v", parked)
				}
				resumed, err := k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "tool_callback", ReceiptRef: "rcpt://resume", IncomingStepSeqID: 2, ExpectedSnapshotHash: created.SnapshotHash})
				mustNoErr(t, err)
				if resumed.NewState != StateRunning {
					t.Fatalf("resume state mismatch: %+v", resumed)
				}
			}
		})
	}
}
func TestCreateRunValidation(t *testing.T) {
	k := NewKernel(Config{}, nil)
	_, err := k.CreateRun(CreateRunRequest{})
	assertKernelErrStatus(t, err, 422)
	_, err = k.CreateRun(CreateRunRequest{RequestID: "req-missing-cps", TenantID: "t", WorkflowID: "w", WorkflowVersion: "v", RiskTier: RiskLow, Snapshot: SnapshotInput{}})
	assertKernelErrStatus(t, err, 409)
	_, err = k.CreateRun(CreateRunRequest{RequestID: "req-invalid-risk", TenantID: "t", WorkflowID: "w", WorkflowVersion: "v", RiskTier: "unknown", Snapshot: SnapshotInput{ContextPolicySpaceHash: "cps"}})
	assertKernelErrStatus(t, err, 422)
}
func TestAdvanceBranches(t *testing.T) {
	base := time.Date(2026, 4, 3, 13, 0, 0, 0, time.UTC)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, port)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)
	_, err = k.AdvanceRun("missing", validAdvanceRequest())
	assertKernelErrStatus(t, err, 404)
	req := validAdvanceRequest()
	req.ExpectedStateVersion = 2
	req.DecisionRef = DecisionRef{DecisionID: "d1", DecisionHash: "h1", DecisionHashKind: "stable"}
	port.confirmed["d1|"+created.RunID+"|"+req.StepID] = true
	port.refs["d1"] = DecisionReference{DecisionID: "d1", RunID: created.RunID, StepID: req.StepID, DecisionHash: "h1", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, req)
	assertKernelErrStatus(t, err, 409)
	req2 := validAdvanceRequest()
	req2.DecisionRef = DecisionRef{DecisionID: "d2", DecisionHash: "h2", DecisionHashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, req2)
	assertKernelErrStatus(t, err, 409)
	run, _ := k.GetRun(created.RunID)
	if run.State != StateSafeguardHold {
		t.Fatalf("expected safeguard hold, got=%s", run.State)
	}
}
func TestAdvanceIdempotencyAndMonotonicity(t *testing.T) {
	base := time.Date(2026, 4, 3, 13, 0, 0, 0, time.UTC)
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}}, port)
	created, _ := k.CreateRun(validCreateRequest())
	req := validAdvanceRequest()
	req.DecisionRef = DecisionRef{DecisionID: "d3", DecisionHash: "h3", DecisionHashKind: "stable"}
	port.confirmed["d3|"+created.RunID+"|"+req.StepID] = true
	port.refs["d3"] = DecisionReference{DecisionID: "d3", RunID: created.RunID, StepID: req.StepID, DecisionHash: "h3", HashValid: true, HashKind: "stable"}
	first, err := k.AdvanceRun(created.RunID, req)
	mustNoErr(t, err)
	second, err := k.AdvanceRun(created.RunID, req)
	mustNoErr(t, err)
	if first.StepHash != second.StepHash {
		t.Fatalf("idempotent replay mismatch")
	}
	bad := validAdvanceRequest()
	bad.ExpectedStateVersion = 2
	bad.IncomingStepSeqID = 1
	bad.IdempotencyKey = "idem-2"
	bad.DecisionRef = DecisionRef{DecisionID: "d4", DecisionHash: "h4", DecisionHashKind: "stable"}
	port.confirmed["d4|"+created.RunID+"|"+bad.StepID] = true
	port.refs["d4"] = DecisionReference{DecisionID: "d4", RunID: created.RunID, StepID: bad.StepID, DecisionHash: "h4", HashValid: true, HashKind: "stable"}
	_, err = k.AdvanceRun(created.RunID, bad)
	assertKernelErrStatus(t, err, 409)
	events := k.Outbox()
	if !hasRunEventType(events, "irreversible_progress_violation_event") {
		t.Fatalf("monotonicity violation must emit irreversible_progress_violation_event")
	}
	if !hasRunEventType(events, "progress_monotonicity_violation") {
		t.Fatalf("monotonicity violation should keep compatibility event")
	}
}
func TestParkResumeMonotonicityEvents(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	_, err := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s-park", IncomingStepSeqID: 0, TokenType: TokenTypePark})
	assertKernelErrStatus(t, err, 409)
	if !hasRunEventType(k.Outbox(), "irreversible_progress_violation_event") {
		t.Fatalf("park monotonicity violation must emit irreversible_progress_violation_event")
	}
	parked, err := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s-park2", IncomingStepSeqID: 1, TokenType: TokenTypePark})
	mustNoErr(t, err)
	_, err = k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "bad-seq", IncomingStepSeqID: 1, ExpectedSnapshotHash: created.SnapshotHash})
	assertKernelErrStatus(t, err, 409)
	if !hasRunEventType(k.Outbox(), "irreversible_progress_violation_event") {
		t.Fatalf("resume monotonicity violation must emit irreversible_progress_violation_event")
	}
}
func TestParkResumeBranches(t *testing.T) {
	base := time.Date(2026, 4, 3, 13, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, ContinuationTTL: 1 * time.Second}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	parkReq := ParkRunRequest{ExpectedStateVersion: 1, StepID: "step-park", IncomingStepSeqID: 1, TokenType: TokenTypePark, ParkReason: "wait"}
	parked, err := k.ParkRun(created.RunID, parkReq)
	mustNoErr(t, err)
	_, err = k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "resume", IncomingStepSeqID: 2, ExpectedSnapshotHash: created.SnapshotHash})
	mustNoErr(t, err)
	_, err = k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "resume2", IncomingStepSeqID: 3, ExpectedSnapshotHash: created.SnapshotHash})
	assertKernelErrStatus(t, err, 409)
	created2, _ := k.CreateRun(validCreateRequestWithRisk("medium"))
	parked2, _ := k.ParkRun(created2.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s2", IncomingStepSeqID: 1, TokenType: TokenTypePark})
	_, err = k.ResumeRun(created2.RunID, ResumeRunRequest{ContinuationToken: parked2.ContinuationToken, ResumeReason: "late", IncomingStepSeqID: 2, ExpectedSnapshotHash: created2.SnapshotHash})
	if err != nil {
		t.Fatalf("unexpected error before expiry: %v", err)
	}
	created3, _ := k.CreateRun(validCreateRequest())
	parked3, _ := k.ParkRun(created3.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s3", IncomingStepSeqID: 1, TokenType: TokenTypePark, TTLSeconds: 1})
	k.cfg.Clock = func() time.Time {
		return base.Add(2 * time.Second)
	}
	_, err = k.ResumeRun(created3.RunID, ResumeRunRequest{ContinuationToken: parked3.ContinuationToken, ResumeReason: "expired", IncomingStepSeqID: 2, ExpectedSnapshotHash: created3.SnapshotHash})
	assertKernelErrStatus(t, err, 410)
}
func TestResumeSnapshotMismatchAndPathConflicts(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	parked, _ := k.ParkRun(created.RunID, ParkRunRequest{ExpectedStateVersion: 1, StepID: "s1", IncomingStepSeqID: 1, TokenType: TokenTypePark})
	_, err := k.ResumeRun(created.RunID, ResumeRunRequest{ContinuationToken: parked.ContinuationToken, ResumeReason: "bad-snapshot", IncomingStepSeqID: 2, ExpectedSnapshotHash: "wrong"})
	assertKernelErrStatus(t, err, 412)
	_, err = k.ResumeRun("missing", ResumeRunRequest{})
	assertKernelErrStatus(t, err, 404)
}
func TestAbortAndTerminalTransitions(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	view, err := k.AbortRun(created.RunID, AbortRunRequest{Reason: "manual"})
	mustNoErr(t, err)
	if view.State != StateAborted {
		t.Fatalf("expected aborted, got=%s", view.State)
	}
	view2, err := k.AbortRun(created.RunID, AbortRunRequest{Reason: "again"})
	mustNoErr(t, err)
	if view2.State != StateAborted {
		t.Fatalf("expected aborted")
	}
}
func TestSweepTTLAndZombie(t *testing.T) {
	base := time.Date(2026, 4, 3, 13, 0, 0, 0, time.UTC)
	k := NewKernel(Config{Clock: func() time.Time {
		return base
	}, ZombieNoProgressWindow: 1 * time.Minute, RunMaxLifetime: map[string]time.Duration{RiskLow: 1 * time.Minute, RiskMedium: 1 * time.Minute, RiskHigh: 1 * time.Minute, RiskCritical: 1 * time.Minute}}, nil)
	low, _ := k.CreateRun(validCreateRequestWithRisk(RiskLow))
	high, _ := k.CreateRun(validCreateRequestWithRisk(RiskHigh))
	_ = k.FlagRunRisk(high.RunID, true, false)
	ttl := k.SweepTTL(base.Add(2 * time.Minute))
	if ttl.ForceReviewRequiredCount == 0 || ttl.ForceAbortCount == 0 {
		t.Fatalf("ttl sweep should force review and force abort: %+v", ttl)
	}
	zombieRun, _ := k.CreateRun(validCreateRequestWithRisk(RiskMedium))
	z1 := k.SweepZombie(base.Add(5 * time.Minute))
	if z1.ZombieTerminatedCount != 0 {
		t.Fatalf("first zombie sweep should not terminate")
	}
	z2 := k.SweepZombie(base.Add(6 * time.Minute))
	if z2.ZombieTerminatedCount == 0 {
		t.Fatalf("second zombie sweep should terminate")
	}
	view, _ := k.GetRun(zombieRun.RunID)
	if view.State != StateForceReviewRequired && view.State != StateForceAbort {
		t.Fatalf("unexpected zombie end state: %s", view.State)
	}
	_ = low
}
func TestCopiesAndHelpers(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, _ := k.CreateRun(validCreateRequest())
	out := k.Outbox()
	if len(out) == 0 {
		t.Fatalf("expected outbox")
	}
	out[0].EventType = "tamper"
	out2 := k.Outbox()
	if out2[0].EventType == "tamper" {
		t.Fatalf("outbox must be copied")
	}
	si := k.StepIntegrities(created.RunID)
	if len(si) != 0 {
		t.Fatalf("new run should have no steps")
	}
	if !isValidTokenType(TokenTypeApproval) || isValidTokenType("bad") {
		t.Fatalf("token type helper mismatch")
	}
	if !isValidState(StateRunning) || isValidState("x") {
		t.Fatalf("state helper mismatch")
	}
	if !isAllowedTransition(StateRunning, StateParked) || isAllowedTransition(StateCompleted, StateRunning) {
		t.Fatalf("transition helper mismatch")
	}
	if nextActionByState(StateCompleted) != "done" {
		t.Fatalf("next action mismatch")
	}
	if normalizeState("running") != StateRunning {
		t.Fatalf("normalize state mismatch")
	}
	if normalizeRisk("HIGH") != RiskHigh {
		t.Fatalf("normalize risk mismatch")
	}
	if !isValidRisk(RiskLow) || isValidRisk("x") {
		t.Fatalf("risk helper mismatch")
	}
}
func TestKernelErrorAndNotFoundHelpers(t *testing.T) {
	err := kernelErr(409, "CODE", "message", "r1")
	var ke *KernelError
	if !errors.As(err, &ke) {
		t.Fatalf("expected kernel error type")
	}
	if ke.Error() != "message" {
		t.Fatalf("error message mismatch")
	}
	k := NewKernel(Config{}, nil)
	_, err = k.GetRun("missing")
	assertKernelErrStatus(t, err, 404)
}
func TestSortedRunsHelper(t *testing.T) {
	k := NewKernel(Config{}, nil)
	a, _ := k.CreateRun(validCreateRequestWithWorkflow("wf-b"))
	b, _ := k.CreateRun(validCreateRequestWithWorkflow("wf-a"))
	_ = a
	_ = b
	sorted := sortedRuns(k.runs)
	if len(sorted) != len(k.runs) {
		t.Fatalf("sorted length mismatch")
	}
}
func loadRunCases(t *testing.T) []runCase {
	t.Helper()
	path := filepath.Join("..", "..", "testdata", "run_cases.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read run cases: %v", err)
	}
	var input runCaseFile
	if err := json.Unmarshal(raw, &input); err != nil {
		t.Fatalf("unmarshal run cases: %v", err)
	}
	return input.Cases
}
func validCreateRequest() CreateRunRequest {
	return validCreateRequestWithRisk(RiskLow)
}
func validCreateRequestWithRisk(risk string) CreateRunRequest {
	requestID := fmt.Sprintf("req-%d", atomic.AddInt64(&testRequestSeq, 1))
	return CreateRunRequest{RequestID: requestID, TenantID: "tenant-a", WorkflowID: "wf-1", WorkflowVersion: "v1", RiskTier: risk, InputPayloadRef: "obj://input", Snapshot: SnapshotInput{PolicyBundleID: "pb-1", ModelProfileID: "mp-1", DependencyBundleID: "db-1", SkillBundleSetHash: "skills-1", ContextPolicySpaceHash: "cps-1"}}
}

var testRequestSeq int64

func validCreateRequestWithWorkflow(workflow string) CreateRunRequest {
	req := validCreateRequest()
	req.WorkflowID = workflow
	return req
}
func validAdvanceRequest() AdvanceRunRequest {
	return AdvanceRunRequest{
		ExpectedStateVersion:   1,
		StepID:                 "step-1",
		StepVersion:            "v1",
		IdempotencyKey:         "idem-1",
		ExecutionReceiptRef:    "ticket://t-default",
		ExecutionUsedResources: map[string]float64{"tokens": 1},
		IncomingStepSeqID:      1,
		InputHash:              "in-hash",
		OutputHash:             "out-hash",
		NextState:              StateRunning,
	}
}
func assertKernelErrStatus(t *testing.T, err error, status int) {
	t.Helper()
	if err == nil {
		t.Fatalf("expected error status=%d, got nil", status)
	}
	var ke *KernelError
	if !errors.As(err, &ke) {
		t.Fatalf("expected KernelError, got=%T err=%v", err, err)
	}
	if ke.StatusCode != status {
		t.Fatalf("status mismatch: got=%d want=%d err=%+v", ke.StatusCode, status, ke)
	}
}
func mustNoErr(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
func TestHelperFunctionsCoverage(t *testing.T) {
	values := []string{"c", "a", "b"}
	slices.Sort(values)
	if values[0] != "a" {
		t.Fatalf("sort sanity failed")
	}
	if hashJSON(map[string]string{"a": "b"}) == "" {
		t.Fatalf("hash should not be empty")
	}
}
func hasRunEventType(events []KernelEvent, eventType string) bool {
	for _, e := range events {
		if e.EventType == eventType {
			return true
		}
	}
	return false
}

func TestObligationLimitParamHelpers(t *testing.T) {
	if n, ok := parseLimitValue(""); ok || n != 0 {
		t.Fatalf("empty limit should fail parse")
	}
	if n, ok := parseLimitValue("max:12"); !ok || n != 12 {
		t.Fatalf("prefixed limit parse mismatch: n=%d ok=%v", n, ok)
	}
	if n, ok := parseLimitValue("abc"); ok || n != 0 {
		t.Fatalf("invalid numeric limit should fail parse")
	}
	if n, ok := parseLimitValue("-1"); ok || n != 0 {
		t.Fatalf("negative limit should fail parse")
	}

	baseReq := AdvanceRunRequest{
		InputHash:         "input-hash",
		OutputHash:        "output-hash",
		IncomingStepSeqID: 5,
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "max_input_hash_len", Value: "64"}); err != nil {
		t.Fatalf("expected max_input_hash_len pass: %v", err)
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "max_output_hash_len", Value: "64"}); err != nil {
		t.Fatalf("expected max_output_hash_len pass: %v", err)
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "max_step_seq_id", Value: "6"}); err != nil {
		t.Fatalf("expected max_step_seq_id pass: %v", err)
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "max_input_hash_len", Value: "3"}); err == nil {
		t.Fatalf("expected input hash limit violation")
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "max_output_hash_len", Value: "3"}); err == nil {
		t.Fatalf("expected output hash limit violation")
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "max_step_seq_id", Value: "3"}); err == nil {
		t.Fatalf("expected step seq limit violation")
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "unsupported_target", Value: "10"}); err == nil {
		t.Fatalf("expected unsupported target violation")
	}
	if err := enforceLimitParamObligation(baseReq, DecisionObligation{Target: "max_step_seq_id", Value: "bad"}); err == nil {
		t.Fatalf("expected invalid value parse error")
	}
}

func TestAdvanceRunObligationConsumptionBranches(t *testing.T) {
	newKernel := func() (*Kernel, *fakeDecisionPort, CreateRunResponse) {
		port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
		k := NewKernel(Config{}, port)
		created, err := k.CreateRun(validCreateRequest())
		mustNoErr(t, err)
		return k, port, created
	}

	t.Run("attach_tag_emit_audit_and_require_template_pass", func(t *testing.T) {
		k, port, created := newKernel()
		req := validAdvanceRequest()
		req.ExecutionReceiptRef = "rcpt://tool/template/high_risk_write_template"
		req.DecisionRef = DecisionRef{DecisionID: "d-ob-pass", DecisionHash: "h-ob-pass", DecisionHashKind: "stable"}
		port.confirmed["d-ob-pass|"+created.RunID+"|"+req.StepID] = true
		port.refs["d-ob-pass"] = DecisionReference{
			DecisionID:   "d-ob-pass",
			RunID:        created.RunID,
			StepID:       req.StepID,
			Phase:        "PRE_TOOL",
			DecisionHash: "h-ob-pass",
			HashValid:    true,
			HashKind:     "stable",
			Obligations: []DecisionObligation{
				{Type: "attach_tag", Target: "route", Value: "vip"},
				{Type: "emit_audit", Target: "audit_tag", Value: "obligation_hit"},
				{Type: "require_template", Value: "high_risk_write_template"},
			},
		}
		_, err := k.AdvanceRun(created.RunID, req)
		mustNoErr(t, err)
		view, err := k.GetRun(created.RunID)
		mustNoErr(t, err)
		if view.AttachedTags["route"] != "vip" {
			t.Fatalf("attach_tag obligation not applied: %+v", view.AttachedTags)
		}
		events := k.Outbox()
		if !hasRunEventType(events, "run_obligation_audit_event") {
			t.Fatalf("emit_audit obligation should emit run_obligation_audit_event")
		}
	})

	t.Run("limit_param_violation", func(t *testing.T) {
		k, port, created := newKernel()
		req := validAdvanceRequest()
		req.DecisionRef = DecisionRef{DecisionID: "d-ob-limit", DecisionHash: "h-ob-limit", DecisionHashKind: "stable"}
		req.InputHash = "very-long-input-hash"
		port.confirmed["d-ob-limit|"+created.RunID+"|"+req.StepID] = true
		port.refs["d-ob-limit"] = DecisionReference{
			DecisionID:   "d-ob-limit",
			RunID:        created.RunID,
			StepID:       req.StepID,
			Phase:        "PRE_TOOL",
			DecisionHash: "h-ob-limit",
			HashValid:    true,
			HashKind:     "stable",
			Obligations: []DecisionObligation{
				{Type: "limit_param", Target: "max_input_hash_len", Value: "4"},
			},
		}
		_, err := k.AdvanceRun(created.RunID, req)
		assertKernelErrStatus(t, err, 409)
		if !hasRunEventType(k.Outbox(), "run_obligation_limit_violation") {
			t.Fatalf("limit_param violation should emit run_obligation_limit_violation")
		}
	})

	t.Run("require_template_missing", func(t *testing.T) {
		k, port, created := newKernel()
		req := validAdvanceRequest()
		req.ExecutionReceiptRef = "rcpt://tool/no_template_here"
		req.DecisionRef = DecisionRef{DecisionID: "d-ob-template", DecisionHash: "h-ob-template", DecisionHashKind: "stable"}
		port.confirmed["d-ob-template|"+created.RunID+"|"+req.StepID] = true
		port.refs["d-ob-template"] = DecisionReference{
			DecisionID:   "d-ob-template",
			RunID:        created.RunID,
			StepID:       req.StepID,
			Phase:        "PRE_TOOL",
			DecisionHash: "h-ob-template",
			HashValid:    true,
			HashKind:     "stable",
			Obligations: []DecisionObligation{
				{Type: "require_template", Value: "expected_template"},
			},
		}
		_, err := k.AdvanceRun(created.RunID, req)
		assertKernelErrStatus(t, err, 409)
		if !hasRunEventType(k.Outbox(), "run_obligation_template_missing") {
			t.Fatalf("template missing should emit run_obligation_template_missing")
		}
	})

	t.Run("require_template_substring_bypass_rejected", func(t *testing.T) {
		k, port, created := newKernel()
		req := validAdvanceRequest()
		req.ExecutionReceiptRef = "rcpt://tool/notes/contains_expected_template_but_not_proof?note=expected_template"
		req.DecisionRef = DecisionRef{DecisionID: "d-ob-template-bypass", DecisionHash: "h-ob-template-bypass", DecisionHashKind: "stable"}
		port.confirmed["d-ob-template-bypass|"+created.RunID+"|"+req.StepID] = true
		port.refs["d-ob-template-bypass"] = DecisionReference{
			DecisionID:   "d-ob-template-bypass",
			RunID:        created.RunID,
			StepID:       req.StepID,
			Phase:        "PRE_TOOL",
			DecisionHash: "h-ob-template-bypass",
			HashValid:    true,
			HashKind:     "stable",
			Obligations: []DecisionObligation{
				{Type: "require_template", Value: "expected_template"},
			},
		}
		_, err := k.AdvanceRun(created.RunID, req)
		assertKernelErrStatus(t, err, 409)
		if !hasRunEventType(k.Outbox(), "run_obligation_template_missing") {
			t.Fatalf("substring bypass must emit run_obligation_template_missing")
		}
	})

	t.Run("phase_mismatch_and_unsupported_type", func(t *testing.T) {
		k, port, created := newKernel()
		req := validAdvanceRequest()
		req.DecisionRef = DecisionRef{DecisionID: "d-ob-phase", DecisionHash: "h-ob-phase", DecisionHashKind: "stable"}
		port.confirmed["d-ob-phase|"+created.RunID+"|"+req.StepID] = true
		port.refs["d-ob-phase"] = DecisionReference{
			DecisionID:   "d-ob-phase",
			RunID:        created.RunID,
			StepID:       req.StepID,
			Phase:        "PRE_TOOL",
			DecisionHash: "h-ob-phase",
			HashValid:    true,
			HashKind:     "stable",
			Obligations: []DecisionObligation{
				{Type: "attach_tag", Target: "x", Value: "y", Phase: "PRE_RELEASE"},
			},
		}
		_, err := k.AdvanceRun(created.RunID, req)
		assertKernelErrStatus(t, err, 409)
		if !hasRunEventType(k.Outbox(), "run_obligation_phase_mismatch") {
			t.Fatalf("phase mismatch should emit run_obligation_phase_mismatch")
		}

		k2, port2, created2 := newKernel()
		req2 := validAdvanceRequest()
		req2.DecisionRef = DecisionRef{DecisionID: "d-ob-unsupported", DecisionHash: "h-ob-unsupported", DecisionHashKind: "stable"}
		port2.confirmed["d-ob-unsupported|"+created2.RunID+"|"+req2.StepID] = true
		port2.refs["d-ob-unsupported"] = DecisionReference{
			DecisionID:   "d-ob-unsupported",
			RunID:        created2.RunID,
			StepID:       req2.StepID,
			Phase:        "PRE_TOOL",
			DecisionHash: "h-ob-unsupported",
			HashValid:    true,
			HashKind:     "stable",
			Obligations: []DecisionObligation{
				{Type: "unknown_obligation_type", Value: "x"},
			},
		}
		_, err = k2.AdvanceRun(created2.RunID, req2)
		assertKernelErrStatus(t, err, 409)
		if !hasRunEventType(k2.Outbox(), "run_obligation_unsupported") {
			t.Fatalf("unsupported type should emit run_obligation_unsupported")
		}
	})

	t.Run("deny_execution_obligation", func(t *testing.T) {
		k, port, created := newKernel()
		req := validAdvanceRequest()
		req.DecisionRef = DecisionRef{DecisionID: "d-ob-deny", DecisionHash: "h-ob-deny", DecisionHashKind: "stable"}
		port.confirmed["d-ob-deny|"+created.RunID+"|"+req.StepID] = true
		port.refs["d-ob-deny"] = DecisionReference{
			DecisionID:   "d-ob-deny",
			RunID:        created.RunID,
			StepID:       req.StepID,
			Phase:        "PRE_TOOL",
			DecisionHash: "h-ob-deny",
			HashValid:    true,
			HashKind:     "stable",
			Obligations: []DecisionObligation{
				{Type: "deny_execution", Value: "blocked_by_policy"},
			},
		}
		_, err := k.AdvanceRun(created.RunID, req)
		assertKernelErrStatus(t, err, 409)
		if !hasRunEventType(k.Outbox(), "run_obligation_deny_execution") {
			t.Fatalf("deny_execution should emit run_obligation_deny_execution")
		}
	})

	t.Run("non_executable_decision_value", func(t *testing.T) {
		k, port, created := newKernel()
		req := validAdvanceRequest()
		req.DecisionRef = DecisionRef{DecisionID: "d-not-exec", DecisionHash: "h-not-exec", DecisionHashKind: "stable"}
		port.confirmed["d-not-exec|"+created.RunID+"|"+req.StepID] = true
		port.refs["d-not-exec"] = DecisionReference{
			DecisionID:   "d-not-exec",
			RunID:        created.RunID,
			StepID:       req.StepID,
			Phase:        "PRE_TOOL",
			Decision:     "fail_closed",
			DecisionHash: "h-not-exec",
			HashValid:    true,
			HashKind:     "stable",
		}
		_, err := k.AdvanceRun(created.RunID, req)
		assertKernelErrStatus(t, err, 409)
		if !hasRunEventType(k.Outbox(), "run_decision_not_executable") {
			t.Fatalf("non executable decision should emit run_decision_not_executable")
		}
	})
}

func TestDecisionAndObligationPhaseHelpers(t *testing.T) {
	if !isExecutableDecision("") {
		t.Fatalf("empty decision should be executable")
	}
	if !isExecutableDecision("allow") || !isExecutableDecision("require_approval") {
		t.Fatalf("allowed decision set mismatch")
	}
	if isExecutableDecision("review_required") || isExecutableDecision("deny") || isExecutableDecision("fail_closed") || isExecutableDecision("block") {
		t.Fatalf("non executable decisions should be rejected")
	}

	if !isObligationPhaseAllowed("PRE_CONTEXT", "PRE_CONTEXT") {
		t.Fatalf("pre_context should allow pre_context")
	}
	if isObligationPhaseAllowed("PRE_CONTEXT", "PRE_TOOL") {
		t.Fatalf("pre_context should not allow pre_tool")
	}
	if !isObligationPhaseAllowed("PRE_TOOL", "PRE_CONTEXT") || !isObligationPhaseAllowed("PRE_TOOL", "PRE_TOOL") {
		t.Fatalf("pre_tool should allow pre_context and pre_tool")
	}
	if isObligationPhaseAllowed("PRE_RESUME", "PRE_TOOL") {
		t.Fatalf("pre_resume should not be accepted on advance path")
	}
}

func TestTemplateEvidenceExtractionAndMatching(t *testing.T) {
	t.Run("query_template_id", func(t *testing.T) {
		ref := "rcpt://tool/execute?template_id=high_risk_write_template"
		if !receiptRefHasTemplateEvidence(ref, "high_risk_write_template") {
			t.Fatalf("expected query template_id to match")
		}
	})

	t.Run("path_template_segment", func(t *testing.T) {
		ref := "rcpt://tool/template/high_risk_write_template"
		if !receiptRefHasTemplateEvidence(ref, "high_risk_write_template") {
			t.Fatalf("expected /template/{id} to match")
		}
	})

	t.Run("substring_bypass_rejected", func(t *testing.T) {
		ref := "rcpt://tool/notes/contains_high_risk_write_template_but_not_proof?note=high_risk_write_template"
		if receiptRefHasTemplateEvidence(ref, "high_risk_write_template") {
			t.Fatalf("substring presence must not satisfy template evidence")
		}
	})

	t.Run("template_scheme_and_mixed_keys", func(t *testing.T) {
		ids := extractTemplateEvidenceIDs("template://risk_template_v2?template=legacy&templateId=camel_id")
		if _, ok := ids["risk_template_v2"]; !ok {
			t.Fatalf("template scheme host should be extracted")
		}
		if _, ok := ids["legacy"]; !ok {
			t.Fatalf("template query key should be extracted")
		}
		if _, ok := ids["camel_id"]; !ok {
			t.Fatalf("templateId query key should be extracted")
		}
	})

	t.Run("templates_path_and_sorted_ids", func(t *testing.T) {
		ids := extractTemplateEvidenceIDs("rcpt://tool/templates/beta_template?template_id=alpha_template")
		if _, ok := ids["alpha_template"]; !ok {
			t.Fatalf("expected query template id")
		}
		if _, ok := ids["beta_template"]; !ok {
			t.Fatalf("expected /templates/{id}")
		}
		sorted := sortedTemplateEvidenceIDs("rcpt://tool/templates/beta_template?template_id=alpha_template")
		if len(sorted) != 2 || sorted[0] != "alpha_template" || sorted[1] != "beta_template" {
			t.Fatalf("sorted template ids mismatch: %+v", sorted)
		}
	})

	t.Run("empty_or_invalid_refs", func(t *testing.T) {
		if !receiptRefHasTemplateEvidence("rcpt://tool/noop", "") {
			t.Fatalf("empty required template should always pass")
		}
		if got := sortedTemplateEvidenceIDs(""); got != nil {
			t.Fatalf("empty receipt ref should return nil sorted ids, got=%v", got)
		}
		invalid := extractTemplateEvidenceIDs("://bad%%%")
		if len(invalid) != 0 {
			t.Fatalf("invalid receipt ref should not extract template ids: %+v", invalid)
		}
	})

	t.Run("candidate_normalization", func(t *testing.T) {
		m := map[string]struct{}{}
		addTemplateEvidenceCandidate(m, "/nested/path/final_id/")
		if _, ok := m["final_id"]; !ok {
			t.Fatalf("candidate normalization should keep final segment")
		}
		addTemplateEvidenceCandidate(m, "   ")
		if len(m) != 1 {
			t.Fatalf("blank candidate should be ignored: %+v", m)
		}
	})
}

func TestRunObligationHardGuardsPreventAdvanceStateChange(t *testing.T) {
	port := &fakeDecisionPort{confirmed: map[string]bool{}, refs: map[string]DecisionReference{}}
	k := NewKernel(Config{}, port)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)

	req := validAdvanceRequest()
	req.StepID = "step-ob-hard-1"
	req.IdempotencyKey = "idem-ob-hard-1"
	req.DecisionRef = DecisionRef{DecisionID: "d-ob-hard-1", DecisionHash: "h-ob-hard-1", DecisionHashKind: "stable"}
	port.confirmed["d-ob-hard-1|"+created.RunID+"|"+req.StepID] = true
	port.refs["d-ob-hard-1"] = DecisionReference{
		DecisionID:   "d-ob-hard-1",
		RunID:        created.RunID,
		StepID:       req.StepID,
		Phase:        "PRE_TOOL",
		Decision:     "allow",
		DecisionHash: "h-ob-hard-1",
		HashValid:    true,
		HashKind:     "stable",
		Obligations: []DecisionObligation{
			{Type: "require_template", Value: "must_exist_template"},
		},
	}

	before, err := k.GetRun(created.RunID)
	mustNoErr(t, err)
	_, err = k.AdvanceRun(created.RunID, req)
	assertKernelErrStatus(t, err, 409)
	after, err := k.GetRun(created.RunID)
	mustNoErr(t, err)
	// Obligation rejection may move run to safeguard hold, but it must not advance step progress/version.
	if after.CurrentStepSeqID != before.CurrentStepSeqID || after.StateVersion != before.StateVersion {
		t.Fatalf("run progress/state_version must not advance when obligations reject advance: before=%+v after=%+v", before, after)
	}
	if !hasRunEventType(k.Outbox(), "run_obligation_template_missing") {
		t.Fatalf("expected run_obligation_template_missing event")
	}

	req2 := validAdvanceRequest()
	req2.StepID = "step-ob-hard-2"
	req2.IdempotencyKey = "idem-ob-hard-2"
	req2.DecisionRef = DecisionRef{DecisionID: "d-ob-hard-2", DecisionHash: "h-ob-hard-2", DecisionHashKind: "stable"}
	port.confirmed["d-ob-hard-2|"+created.RunID+"|"+req2.StepID] = true
	port.refs["d-ob-hard-2"] = DecisionReference{
		DecisionID:   "d-ob-hard-2",
		RunID:        created.RunID,
		StepID:       req2.StepID,
		Phase:        "PRE_TOOL",
		Decision:     "allow",
		DecisionHash: "h-ob-hard-2",
		HashValid:    true,
		HashKind:     "stable",
		Obligations: []DecisionObligation{
			{Type: "limit_param", Target: "max_step_seq_id", Value: "0"},
		},
	}
	_, err = k.AdvanceRun(created.RunID, req2)
	assertKernelErrStatus(t, err, 409)
	if !hasRunEventType(k.Outbox(), "run_obligation_limit_violation") {
		t.Fatalf("expected run_obligation_limit_violation event")
	}
}

func TestFindActiveContinuationSelectsLatestEligible(t *testing.T) {
	k := NewKernel(Config{}, nil)
	created, err := k.CreateRun(validCreateRequest())
	mustNoErr(t, err)

	parkedApproval, err := k.ParkRun(created.RunID, ParkRunRequest{
		ExpectedStateVersion: 1,
		StepID:               "step-approval",
		IncomingStepSeqID:    1,
		TokenType:            TokenTypeApproval,
		ParkReason:           "wait_approval",
	})
	mustNoErr(t, err)
	if parkedApproval.NewState != StateAwaitingApproval {
		t.Fatalf("approval parking should enter awaiting_approval, got=%s", parkedApproval.NewState)
	}

	// Resume approval once so first token becomes consumed.
	_, err = k.ResumeRun(created.RunID, ResumeRunRequest{
		ContinuationToken:    parkedApproval.ContinuationToken,
		ResumeReason:         "approved",
		IncomingStepSeqID:    2,
		ExpectedSnapshotHash: created.SnapshotHash,
	})
	mustNoErr(t, err)

	// Create a new approval continuation with higher seq id.
	parkedApproval2, err := k.ParkRun(created.RunID, ParkRunRequest{
		ExpectedStateVersion: 3,
		StepID:               "step-approval",
		IncomingStepSeqID:    3,
		TokenType:            TokenTypeApproval,
		ParkReason:           "wait_approval_again",
	})
	mustNoErr(t, err)

	cont, ok := k.FindActiveContinuation(created.RunID, "step-approval", TokenTypeApproval)
	if !ok {
		t.Fatalf("expected active approval continuation")
	}
	if cont.ContinuationID != parkedApproval2.ContinuationToken {
		t.Fatalf("expected latest active approval continuation, got=%+v", cont)
	}
	if _, ok := k.FindActiveContinuation("", "step-approval", TokenTypeApproval); ok {
		t.Fatalf("empty run id should not resolve continuation")
	}
}

func TestFindActiveContinuationAndCleanupBranchCoverage(t *testing.T) {
	now := time.Date(2026, 4, 8, 12, 0, 0, 0, time.UTC)
	k := NewKernel(Config{
		Clock:                 func() time.Time { return now },
		ContinuationRetention: 2 * time.Second,
	}, nil)

	k.mu.Lock()
	k.continuations["nil"] = nil
	consumedAt := now.Add(-10 * time.Second)
	k.continuations["expired-active"] = &Continuation{
		ContinuationID: "ct-expired-active",
		RunID:          "run-cov",
		StepID:         "step-cov",
		TokenType:      TokenTypeApproval,
		StepSeqID:      1,
		Status:         "active",
		CreatedAt:      now.Add(-20 * time.Second),
		ExpiresAt:      now.Add(-5 * time.Second),
	}
	k.continuations["consumed-old"] = &Continuation{
		ContinuationID: "ct-consumed-old",
		RunID:          "run-cov",
		StepID:         "step-cov",
		TokenType:      TokenTypePark,
		StepSeqID:      2,
		Status:         "consumed",
		CreatedAt:      now.Add(-20 * time.Second),
		ExpiresAt:      now.Add(-10 * time.Second),
		ConsumedAt:     &consumedAt,
	}
	k.continuations["active-good"] = &Continuation{
		ContinuationID: "ct-active-good",
		RunID:          "run-cov",
		StepID:         "step-cov",
		TokenType:      TokenTypeApproval,
		StepSeqID:      3,
		Status:         "active",
		CreatedAt:      now.Add(-1 * time.Second),
		ExpiresAt:      now.Add(10 * time.Second),
	}
	k.mu.Unlock()

	if _, ok := k.FindActiveContinuation("run-cov", "step-cov", TokenTypeCallback); ok {
		t.Fatalf("token type mismatch should not return continuation")
	}
	if got, ok := k.FindActiveContinuation("run-cov", "step-cov", TokenTypeApproval); !ok || got.ContinuationID != "ct-active-good" {
		t.Fatalf("expected active approval continuation, got=%+v ok=%v", got, ok)
	}

	sweep := k.SweepTTL(now.Add(20 * time.Second))
	if sweep.DeletedContinuations == 0 {
		t.Fatalf("expected continuation cleanup during sweep")
	}
}
